EventMgtSystem/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from Users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    # TokenObtainPairView,
    TokenRefreshView,
)
from Users.views import MyTokenObtainPairView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='Users/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='Users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="Users/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='Users/password_reset_complete.html'), name='password_reset_complete'),      
    path('login/', auth_views.LoginView.as_view(template_name = 'Users/user_login.html'),name= 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'Users/logout.html'),name= 'logout'),
    path('api/v1/',include('Users.urls')),
    path('api/v1/',include('Events.urls')),
    path('api/v1/',include('Guest.urls')),
    path('api/v1/',include('djoser.urls')),
    path('api/v1/', include('djoser.urls.jwt')),
    # path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Events/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('create_event/', views.createevent,name= 'create_event'),
    path('events_list/', views.EventsList.as_view()),
    path('view_event/<int:pk>/', views.ViewEvent.as_view(),name= 'view_event'),
    path('update_event/<str:pk>/', views.update_event, name="update_event"),
    path('delete_event/<str:pk>/', views.delete_event, name="delete_event"),
    path('print_events/', views.generate_pdf_events,name ='generate_pdf_events'),
    path('print_guests/', views.generate_pdf_guests,name ='generate_pdf_guests'),
    path('send_mail/<int:id>/', views.sendmail,name ='send_mail'),
    #path('guest_registration_email/', views.guest_registration_email,name ='guest_registration_email'),
    path('guest_view_events/', views.guest_view_events, name='guest_view_events'),
    path('view_applications/', views.view_applications,name= 'view_applications'),
    path('view_invites_only_applications/', views.view_invites_only_applications,name= 'view_invites_only_applications'),
    path('reject_application/<str:pk>/', views.reject_application, name="reject_application"),
    path('reject_invites_only_application/<int:id>/', views.reject_invites_only_application, name="reject_invites_only_application"),
    path('print_applications/', views.generate_pdf_applicants,name ='generate_pdf_applicants'),
    path('print_invites_only_applications/', views.generate_pdf_invites_only_applicants,name ='generate_pdf_invites_only_applicants'),
    path('succesful_application/<int:id>/', views.succesful_application,name ='succesful_application'),
    path('ussd_callback/', views.ussd_callback,name = 'ussd_callback'),
    path('events_report/', views.events_report, name = 'events_report'),
]

Guest/urls.py
from django.urls import path,include

from . import views

urlpatterns = [

    path('profile/', views.UserProfiles.as_view(),name= 'profile'),
    path('user-profile/<int:pk>/', views.EditProfile.as_view(),name= 'edit_profile'),
    path('current-user/', views.ProfileDetails.as_view()),
    path('register/',views.register,name = 'register'),
    path('contact/',views.contact,name = 'contact'),
    path('about/',views.about,name = 'about'),
    # path('create_guests_list/', views.create_guests_list,name= 'create_guests_list'),
    path('create_guests_list/', views.guest_registration,name= 'create_guests_list'),
    path('view_guests_list/', views.ViewGuests.as_view(),name= 'view_guests_list'),
    path('update_guests_list/<str:pk>/', views.update_guests_list, name="update_guests_list"),
    path('delete_guests_list/<str:pk>/', views.delete_guests_list, name="delete_guests_list"),
    path('guest_registration/<int:id>/', views.guest_registration,name= 'guest_registration'),
    path('invites_only_application/<int:id>/', views.invites_only_application,name= 'invites_only_application'),
]

Events/models.py
from django.db import models
from django.contrib.auth import get_user_model
from Users.models import User
import datetime


UserModel = get_user_model()
# Create your models here.
class CreateEvent(models.Model):

    EVENTTYPE_CHOICES = (('','Select Event Type'),('Public Event', 'Public Event'),('Invites Only','Invites Only'))
    GUEST_LIST = (('','Select Gender'),('Dr.', 'Dr.'),('Sir','Sir'),('Madam','Madam'),('Mr.','Mr.'),('Mrs.','Mrs.'))
    
    id = models.AutoField(primary_key=True)
    eventtype = models.CharField(max_length=100,choices=EVENTTYPE_CHOICES,default='')
    eventname = models.CharField(max_length=100)
    venue = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    images = models.ImageField(upload_to='uploads/')
    date = models.DateField(default=datetime.date.today)
    guests = models.CharField(max_length=100)
    created_by = models.ForeignKey('Users.User', on_delete=models.CASCADE,related_name='create_events')

    def __str__(self):
        return f'{self.eventname}'

Events/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import *
from Users.models import *
from Users.serializers import *
from .serializers import *
from rest_framework import generics
from rest_framework.views import APIView
from rest_framework import authentication, permissions
from rest_framework.decorators import authentication_classes, permission_classes,api_view
from rest_framework.response import Response
from .utils import render_to_pdf
from django.template.loader import get_template
from django.http import HttpResponse,FileResponse
import smtplib
from email.message import EmailMessage
from django.core.mail import send_mail
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt #for the ussd function
#from africastalking.AfricasTalkingGateway import AfricasTalkingGateway, AfricasTalkingGatewayException#for sms
import africastalking
from .filters import *
from django.core.paginator import Paginator

import io
import reportlab
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter,A4
#from reportlab.lib.units import inch
#from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph

username = 'your africastalking username'
api_key = 'your africastalking api_key'
africastalking.initialize(username, api_key)  
sms = africastalking.SMS


 #CREATE AN EVENT views


#Create an event
@api_view(['POST'])
def createevent(request):
    serializer = CreateEventSerializer(data=request.data)

    if serializer.is_valid():
        serializer.save(created_by=request.user)
        return Response(serializer.data)

#View all events
class EventsList(generics.ListAPIView):
    queryset = CreateEvent.objects.all()
    serializer_class = CreateEventSerializer

#View a particular event
class ViewEvent(generics.RetrieveUpdateDestroyAPIView):
    queryset = CreateEvent.objects.all()
    serializer_class = CreateEventSerializer

#Update events list
@login_required
def update_event(request, pk):

	event = CreateEvent.objects.get(id=pk)
	form2 = CreateEventForm(instance=event,user = request.user)

	if request.method == 'POST':
		form2 = CreateEventForm(request.POST, instance=event,user = request.user)
		if form2.is_valid():
			form2.save()
			return redirect('view_event')

	context = {'form2':form2}
	return render(request, 'Users/update_event.html', context)

#Delete an event
@login_required
def delete_event(request, pk):
	event = CreateEvent.objects.get(id=pk)
	if request.method == "POST":
		event.delete()
		return redirect('view_event')

	context = {'item':event}
	return render(request, 'Users/delete_event.html', context)

#Sending Mails
@login_required
def sendmail(request,id):

    viewevent = get_object_or_404(CreateEvent,id=id)
    guests = viewevent.guests.all()
    recipients =[obj.email for obj in guests]
    msg = EmailMessage()
    msg['Subject']= f'Invitation to {viewevent.eventname} event'
    msg['From']= ''
    viewguests = viewevent.guests.all()
    msg['To']= recipients
    msg.set_content(f'Hello {guest.guestname},\n\n\nI would like to invite you to {viewevent.eventname}.\n\nIt will be held in {viewevent.venue} on {viewevent.date}.\n\nDescription: {viewevent.description}.\n\nKindly confirm your attendance. \n\n\nThank you.')
    
    server = smtplib.SMTP_SSL('your mail host',587)
    server.login('your email address','email password')
    server.send_message(msg)
    server.quit()
    messages.success(request, f'Invites Succesfully sent')
    return redirect('view_event')


#Event Organizer view of public event guests
@login_required
def view_applications(request):
    user = request.user
    viewapplications = GuestRegistration.objects.filter(event_organizer= user)

    publicFilter = GuestRegistrationFilter(request.GET, queryset=viewapplications)
    viewapplications = publicFilter.qs

    paginator = Paginator(viewapplications, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'viewapplications':viewapplications,'publicFilter':publicFilter,'page_obj':page_obj}

    return render(request,'Users/event_applications.html',context)

#Event Organizer view of invites only applications
@login_required
def view_invites_only_applications(request):
    user = request.user
    viewinvitesapplications = InvitesOnlyRegistration.objects.filter(event_organizer=user)

    invitesFilter = InvitesOnlyRegistrationFilter(request.GET, queryset=viewinvitesapplications)
    viewinvitesapplications = invitesFilter.qs

    paginator = Paginator(viewinvitesapplications, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'viewinvitesapplications':viewinvitesapplications,'invitesFilter': invitesFilter,'page_obj':page_obj}

    return render(request,'Users/invites_only_applications.html',context)

#Reject a public event application
@login_required
def reject_application(request, pk):
	application = GuestRegistration.objects.get(id=pk)
	if request.method == "POST":
		application.delete()
		return redirect('view_applications')

	context = {'item':application}
	return render(request, 'Users/reject_application.html', context)

#Reject Invites Only application
@login_required
def reject_invites_only_application(request, id):
    viewinvitesapplications = get_object_or_404(InvitesOnlyRegistration,id=id)
    if request.method == "POST":
        applications = viewinvitesapplications.email
        recipient =[applications]
        subject = 'Unsuccesful Application'
        content = f'Hello {viewinvitesapplications.firstname},\n\nYour application for the event has been declined.\n\nThank you.'
        send_mail(subject, content, settings.EMAIL_HOST_USER,recipient, fail_silently=False)
        messages.success(request, f'Denial email Succesfully sent')
        viewinvitesapplications.delete()
        #sms.send(f'Dear {viewinvitesapplications.firstname}, Your application for the event has been declined.\nThank you.',[f'{viewinvitesapplications.phonenumber}'], callback = reject_invites_only_application)
        return redirect('view_invites_only_applications')
        
    context = {'item':viewinvitesapplications}
    return render(request, 'Users/reject_invites_only_application.html', context)

#Sending Emails to succesful applicants
@login_required
def succesful_application(request,id):
    viewinvitesapplications = get_object_or_404(InvitesOnlyRegistration,id=id)
    applications = viewinvitesapplications.email
    recipient =[applications]
    subject = 'Succesful Application'
    content = f'Hello {viewinvitesapplications.firstname},\n\nYour application  has been approved.\n\nThank you.'
    send_mail(subject, content, settings.EMAIL_HOST_USER,recipient, fail_silently=False)
    messages.success(request, f'Approval email Succesfully sent')
    return redirect('view_invites_only_applications')


#Guest view upcoming events
def guest_view_events(request):
    viewevents = CreateEvent.objects.all()
    

    guestsFilter = GuestViewEventFilter(request.GET, queryset=viewevents)
    viewevents = guestsFilter.qs

    paginator = Paginator(viewevents, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'viewevents':viewevents,'guestsFilter':guestsFilter,'page_obj':page_obj}

    return render(request, 'Users/Guests/guest_view_events.html',context)

                            #USSD CALLBACK View


@csrf_exempt
def ussd_callback(request):
    viewevents = CreateEvent.objects.all()
    if request.method == 'POST':
        session_id = request.POST.get("sessionId")
        service_code = request.POST.get("serviceCode")
        phone_number = request.POST.get("phoneNumber")
        text = request.POST.get("text")
        
        response = ''
        mobilenumber = ''
        username = ''
        
        if text == '':
            response = "CON What event type would you want to attend? \n"
            response += "1. Public \n"
            response += "2. Invites Only"
        elif text == '1':
            response = "CON Choose public event: \n "
            response += "1. Get Together Mombasa \n"
            response += "2. Get Together Nairobi \n"
            response += "3. Get Together Kisumu \n"
            response += "4. Get Together Nakuru \n"
            response += "5. Get Together Naivasha \n"
            response += "6. Get Together Lamu \n"
            response += "7. Get Together Kwale \n"
            response += "98. MORE "
        elif text == '1*98':
            response += "CON 8. Get Together Kakamega \n"
            response += "9. Get Together Busia \n"
            response += "10. Get Together Mandera \n"
            response += "11. Get Together Eldoret \n"
            response += "12. Get Together Wajir \n"
            response += "13. Get Together Uasin Gishu \n"
            response += "00. Exit "
        elif text == '1*98*00':
            response = "END Thank you for using our service"
        elif text == "1*1":
            response = "CON 1. Attend\n"
            response += "2. Go Back\n"
            response +=  "3. Exit"
        
        elif text == "1*1*1":
            response = "CON Enter Your Mobile Number:"
            mobilenumber = text
        elif text == f"{mobilenumber}":
            response = "CON Enter Your Full Names:"
        elif text == f"1*1*1*{username}":
            response = "CON Enter Your ID Number:"
        elif text == "1*1*3":
            response = "END Thank you for using our service"
        elif text == "1*2":
            response = "CON 1. Attend\n"
            response += "2. Go Back\n"
            response +=  "3. Exit"
        elif text == "1*2*1":
            response = "CON Enter Your Full Names:"
        elif text == "1*2*3":

Events/templates/Events/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'Events/main.css' %}">
    <title>Login Page</title>
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="#">Events Management 4 You </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-12">
                {% if messages%} {% for message in messages%}
                <div class="alert alert-{{message.tags}}">{{message}}</div>
                {% endfor %} {% endif %} {% block content %}{% endblock %}
            </div>
        </div>
    </main>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
</body>

</html>

Events/templates/Events/base2.html
{%load static%}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/45760a6434.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'Events/styles.css'%}">
    <title>Event Management System</title>
    <script>
        $(document).ready(function() {
            $("select").change(function() {
                $(this).find("option:selected").each(function() {
                    var optionValue = $(this).attr("value");
                    if (optionValue == "Invites Only") {
                        $("#guestslabel").show();
                        $("#id_guests").show();
                    } else {
                        $("#id_guests").hide();
                        $("#guestslabel").hide();
                    }
                });
            }).change();

        });
    </script>
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand " href="{%url 'events-homepage' %}">EM4U SOLUTIONS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <ul class="navbar-nav ">
                        {%if user.is_authenticated%}
                        <li class="nav-item ">
                            <a class="nav-link active " aria-current="page " href="{% url 'about' %} ">Our Solutions</a>
                        </li>


                        <li class="nav-item ">
                            <a class="nav-link " href="{% url 'contact' %} ">Contact Us</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Guests
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'create_guests_list'%}">Add Guest</a></li>
                                <li><a class="dropdown-item" href="{% url 'view_guests_list'%}">My Guest Lists</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">Queries</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Manage Events
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'create_event'%}">Create Event</a></li>
                                <li><a class="dropdown-item" href="{% url 'view_event'%}">My Events</a></li>
                                <li><a class="dropdown-item" href="{% url 'view_applications'%}">Public Event Attendees</a></li>
                                <li><a class="dropdown-item" href="{% url 'view_invites_only_applications'%}">Invites Only Applications</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">Queries</a></li>
                            </ul>
                        </li>

                        <a class=" nav-link" href="{% url 'profile'%}"><i class="fa fa-user-circle" aria-hidden="true"></i>Profile</a>
                        <a class="nav-link" href="#">Welcome, {{user}}</a>
                        <a class="nav-link" href="{% url 'logout'%}">Logout</a> {% else %}
                        <li class="nav-item ">
                            <a class="nav-link active " aria-current="page " href="# ">Our Solutions</a>
                        </li>

                        <li class="nav-item ">
                            <a class="nav-link " href="{% url 'about' %} ">About</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link " href="{% url 'contact' %} ">Contact Us</a>
                        </li>


                        <a class="nav-link" href="{% url 'login'%}"><i class="fa fa-user-circle" aria-hidden="true"></i>Login</a> {% endif %}



                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container" id="body-content">
        {%block content%}
        <div class="row ">
            <div class="col-md-6 " style="font-family: 'Montserrat', sans-serif; ">
                <h1>Event</h1>
                <h1>Management</h1>
                <h1>Software</h1>
                <p>Our Events Management System helps you simplify event planning for all your virtual,hybrid and in-person events. It has the power and flexibility global enterprises need and the scalability that event organizers love.</p>
                {% if user.is_authenticated%}{%else%}
                <a href="{% url 'guest_view_events' %}"><button id="book-now" class="btn btn-outline-info">View Upcoming Events</button></a> {% endif %}
            </div>

            <div class="col-md-6 ">
                <img src="https://www.pexels.com/photo/572056/download/?search_query=computer%20dashboard&tracking_id=phl4wem2j6" height="300px " width="100%" style="border: none;">

            </div>
        </div>
    </div>

    {%endblock%}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js " integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW " crossorigin="anonymous "></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js " integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU " crossorigin="anonymous "></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js " integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj " crossorigin="anonymous "></script>
    -->
    <footer>
        <p>
            Created with <i class="fa fa-heart"></i> by
            <a target="_blank" href="">SammyB</a>
        </p>
    </footer>
</body>

</html>

Events/templates/Events/index.html
{% extends 'Events/base2.html' %}

Events/templates/Events/mainpage.html
{% extends 'Events/base2.html%} {%block content%} {%endblock% content%}